// Deliverable H — the colour panel: one panel, three targets, and they never touch each other
const T=require('./harness.js');
let pass=0, fail=0;
const check=(name,ok,got)=>{ (ok?pass++:fail++); console.log(`${ok?'PASS':'FAIL'}  ${name}${ok?'':'   got: '+got}`); };
const reset=()=>{ T.loadState(T.freshState()); T.clearSel(); T.hideColorPop(); };
const ring=pw=>{ T.setToolRaw('ring'); T.addRing(pw); if(T.flo()) T.commitFloat(); };

console.log('--- H6a  the fill colour stands on its own');
reset();
check('H6a nothing is open to start with', T.cpop()===null, String(T.cpop()));
check('H6a the fill colour starts at Light Glaucous Blue', T.fillColor()==='#a5c8d1', T.fillColor());
T.openColorPop({kind:'fill'}, null);
check('H6a the panel knows it is colouring the fill', T.cpop().target.kind==='fill' && T.cpopHeading()==='Fill colour', T.cpopHeading());
T.applyPopColor('#cc1236');
check('H6a a pick changes the fill colour', T.fillColor()==='#cc1236', T.fillColor());
check('H6a and leaves the layer ink black', T.state().layers[0].color==='#000000', T.state().layers[0].color);
const depth0=T.undoDepth();
T.applyPopColor('#006eb8');
check('H6a a fill pick is not an undo step: nothing in the drawing changed', T.undoDepth()===depth0, `${T.undoDepth()} vs ${depth0}`);
T.popDefault();
check('H6a Default puts the fill colour back', T.fillColor()==='#a5c8d1', T.fillColor());
T.applyPopColor('#cc1236');
ring({x:0,y:0}); T.fillRing({x:0,y:0});
check('H6a the Fill tool paints with it', T.state().fills.length===1 && T.state().fills[0].color==='#cc1236', JSON.stringify(T.state().fills[0]));
const svg=T.exportSVG();
check('H6a the SVG shows the fill in that colour', /<polygon[^>]*fill="#cc1236"/.test(svg), (svg.match(/<polygon[^>]*>/)||[''])[0].slice(0,90));
check('H6a while the bonds are still the layer ink', /<line[^>]*stroke="#000000"/.test(svg), (svg.match(/<line[^>]*>/)||[''])[0].slice(0,90));

console.log('\n--- H6b  a layer ink is a separate target');
T.hideColorPop();
T.openColorPop({kind:'layer', id:1}, null);
check('H6b the heading names the layer', T.cpopHeading()==='Layer 1 ink', T.cpopHeading());
check('H6b and it reads that layer\'s current colour', T.cpopColor()==='#000000', T.cpopColor());
const depth1=T.undoDepth();
T.applyPopColor('#489b6e');
check('H6b a pick changes the layer ink', T.state().layers[0].color==='#489b6e', T.state().layers[0].color);
check('H6b and leaves the fill colour alone', T.fillColor()==='#cc1236', T.fillColor());
check('H6b one pick is one undo step', T.undoDepth()===depth1+1, `${T.undoDepth()} vs ${depth1+1}`);
T.applyPopColor('#4f4086'); T.applyPopColor('#82241f');
check('H6b two more picks in the same opening add no further steps', T.undoDepth()===depth1+1, `${T.undoDepth()} vs ${depth1+1}`);
T.undo();
check('H6b and one undo puts the ink back to black', T.state().layers[0].color==='#000000', T.state().layers[0].color);
check('H6b undo also closes the panel', T.cpop()===null, JSON.stringify(T.cpop()));

console.log('\n--- H6c  a bond and an arrow are targets of their own');
reset(); T.setFillColor('#a5c8d1');
ring({x:0,y:0});
const b=T.state().bonds[0];
T.openColorPop({kind:'bond', obj:b}, null);
check('H6c the heading says Bond colour', T.cpopHeading()==='Bond colour', T.cpopHeading());
check('H6c with no override it shows the layer ink', T.cpopColor()==='#000000', T.cpopColor());
T.applyPopColor('#f37420');
check('H6c a pick sets the bond colour only', b.color==='#f37420' && T.state().layers[0].color==='#000000' && T.fillColor()==='#a5c8d1', `${b.color}/${T.state().layers[0].color}/${T.fillColor()}`);
T.popDefault();
check('H6c Default removes the override rather than painting it black', b.color===undefined, String(b.color));
T.applyPopColor('#f37420');
check('H6c the SVG carries the per-bond colour beside the layer ink', /stroke="#f37420"/.test(T.exportSVG()) && /stroke="#000000"/.test(T.exportSVG()), 'one of the two is missing');
// a stale object reference must not be written through
check('H6c the target is valid while the bond is in the drawing', T.cpopValid()===true, T.cpopValid());
T.undo();
check('H6c undo closes a panel pointing at a bond', T.cpop()===null, JSON.stringify(T.cpop()));
T.openColorPop({kind:'bond', obj:b}, null);
check('H6c a bond that is no longer in state is not a valid target', T.cpopValid()===false, T.cpopValid());
const snap=JSON.stringify(T.state());
T.applyPopColor('#cc1236');
check('H6c and a pick on it is dropped, changing nothing', JSON.stringify(T.state())===snap && T.cpop()===null, 'the stale bond was written through');
// arrows
reset(); T.setGraphicKind('arrow'); T.placeGraphic({x:0,y:0},{x:4,y:0});
const g=T.state().graphics[0];
T.openColorPop({kind:'graphic', obj:g}, null);
check('H6c the heading says Arrow colour', T.cpopHeading()==='Arrow colour', T.cpopHeading());
T.applyPopColor('#6450a1');
check('H6c a pick sets the arrow colour', g.color==='#6450a1', String(g.color));
check('H6c and the SVG follows', /stroke="#6450a1"/.test(T.exportSVG()), 'not in the SVG');
T.popDefault();
check('H6c Default removes it', g.color===undefined, String(g.color));

console.log('\n--- H6d  the ribbon and the panel lifecycle');
reset(); T.hideColorPop();
T.setTool('ring');
check('H6d the Fill button carries no chip when Fill is not active', T.fillLabel()==='Fill', T.fillLabel());
T.setTool('fill');
check('H6d selecting Fill opens the panel on the fill colour', T.cpop()!==null && T.cpop().target.kind==='fill', JSON.stringify(T.cpop()&&T.cpop().target));
check('H6d and the button carries the chip', /class="chip"/.test(T.fillLabel()) && T.fillLabel().includes('#a5c8d1'), T.fillLabel());
T.setTool('fill');
check('H6d choosing Fill again closes the panel', T.cpop()===null, JSON.stringify(T.cpop()));
T.setTool('fill');
check('H6d and again reopens it', T.cpop()!==null, JSON.stringify(T.cpop()));
T.setTool('bond');
check('H6d leaving Fill hides the panel', T.cpop()===null, JSON.stringify(T.cpop()));
check('H6d and the chip goes with it', T.fillLabel()==='Fill', T.fillLabel());
// a custom swatch is added from whatever the panel is pointed at
T.setCustomColors([]);
T.openColorPop({kind:'fill'}, null); T.applyPopColor('#12354e');
check('H6d the panel reports the colour it is holding', T.cpopColor()==='#12354e', T.cpopColor());

console.log('\n--- K  colouring the things a layer used to colour for you');
const asSVG=()=>T.exportSVG();
const prim=k=>T.layerPrimitives(T.state().layers[0],false).filter(o=>o.k===k);
reset(); T.setFillColor('#a5c8d1');
ring({x:0,y:0});
const a0=T.state().atoms[0];
a0.el='N'; a0.radical=1; a0.color='#cc1236';
check('K an atom colour reaches its label primitive', prim('text').some(o=>o.color==='#cc1236'), JSON.stringify(prim('text').map(o=>o.color)));
check('K and its radical dot', prim('dot').some(o=>o.color==='#cc1236'), JSON.stringify(prim('dot').map(o=>o.color)));
check('K the SVG draws the label in it', /<text[^>]*fill="#cc1236"/.test(asSVG()), (asSVG().match(/<text[^>]*>/)||[''])[0].slice(0,80));
check('K and the dot too, which it used to paint layer ink regardless', /<circle[^>]*fill="#cc1236"/.test(asSVG()), (asSVG().match(/<circle[^>]*>/g)||[]).join(' ').slice(0,120));
check('K while the bonds stay the layer ink', /<line[^>]*stroke="#000000"/.test(asSVG()), 'the bonds changed colour');
let emf=T.emfBuild();
check('K the EMF is built without error and is not empty', emf&&emf.length>88, emf&&emf.length);
// a Clar circle and a free text label
T.state().sextets.push({x:0,y:0,layer:1,color:'#489b6e'});
T.state().texts.push({x:0,y:4,layer:1,text:'label',size:0.9,color:'#6450a1'});
check('K a Clar circle carries its own colour', prim('ring').some(o=>o.color==='#489b6e'), JSON.stringify(prim('ring').map(o=>o.color)));
check('K which reaches the SVG, where a ring used to be layer ink only', /<circle[^>]*stroke="#489b6e"/.test(asSVG()), 'not in the SVG');
check('K and a text label carries its own', /<text[^>]*fill="#6450a1"/.test(asSVG()), 'not in the SVG');
check('K none of it disturbs the chemical export', (()=>{ const S=T.exportStructure(true,15); return S && S.atoms.length===6; })(), 'the structure changed');

console.log('\n--- K  colouring a whole selection at once');
reset(); T.setRingMode('benzene'); ring({x:0,y:0});
T.fillRing({x:0,y:0});
T.setGraphicKind('arrow'); T.placeGraphic({x:4,y:0},{x:8,y:0});
const arrow=T.state().graphics[0];
T.state().texts.push({x:0,y:4,layer:1,text:'label',size:0.9});
T.selectAllActive();
const tg=T.selColorTargets();
check('K the selection derives the bonds between its atoms', tg.atoms.length===6 && tg.bonds.length===6, `${tg.atoms.length} atoms, ${tg.bonds.length} bonds`);
check('K and carries the fill, the text and the arrow', tg.fills.length===1 && tg.texts.length===1 && tg.graphics.length===1, `${tg.fills.length}/${tg.texts.length}/${tg.graphics.length}`);
T.hideColorPop(); T.openColorPop({kind:'sel'}, null);
check('K the panel names what it is about to colour', /^Selection colour/.test(T.cpopHeading()), T.cpopHeading());
const d0=T.undoDepth();
T.applyPopColor('#f37420');
check('K every atom took the colour', T.state().atoms.every(a=>a.color==='#f37420'), T.state().atoms.filter(a=>a.color!=='#f37420').length+' missed');
check('K every enclosed bond too', T.state().bonds.every(b=>b.color==='#f37420'), T.state().bonds.filter(b=>b.color!=='#f37420').length+' missed');
check('K and the text, the arrow and the fill', T.state().texts[0].color==='#f37420' && arrow.color==='#f37420' && T.state().fills[0].color==='#f37420', 'one of them missed');
check('K one pick is one undo step', T.undoDepth()===d0+1, `${T.undoDepth()} vs ${d0+1}`);
T.applyPopColor('#1a7444');
check('K a second pick in the same opening adds no step', T.undoDepth()===d0+1, T.undoDepth());
check('K the SVG carries it on lines and text alike', /<line[^>]*stroke="#1a7444"/.test(asSVG()) && /<text[^>]*fill="#1a7444"/.test(asSVG()), 'not in the SVG');
T.popDefault();
check('K Default drops the overrides', T.state().atoms.every(a=>a.color===undefined) && T.state().bonds.every(b=>b.color===undefined), 'an override survived');
check('K and leaves the ring fill alone, since a fill has no ink to fall back to', T.state().fills[0].color==='#1a7444', String(T.state().fills[0].color));
T.undo();
check('K undo closes a panel pointing at a selection', T.cpop()===null, JSON.stringify(T.cpop()));
T.openColorPop({kind:'sel'}, null);
check('K an empty selection is not a valid target', T.cpopValid()===false, T.cpopValid());
// a bond only takes the colour when BOTH its atoms are selected
reset(); ring({x:0,y:0});
T.clearSel(); T.sel().atoms.add(T.state().atoms[0].id); T.sel().atoms.add(T.state().atoms[1].id);
T.hideColorPop(); T.openColorPop({kind:'sel'}, null); T.applyPopColor('#cc1236');
const coloured=T.state().bonds.filter(b=>b.color==='#cc1236');
check('K exactly the one bond between the two selected atoms', coloured.length===1, coloured.length);
check('K and only those two atoms', T.state().atoms.filter(a=>a.color==='#cc1236').length===2, T.state().atoms.filter(a=>a.color==='#cc1236').length);

console.log('\n--- K  a colour is part of the drawing');
reset(); ring({x:0,y:0});
T.state().atoms[0].color='#b71f57'; T.state().atoms[0].el='N';
const round=JSON.parse(JSON.stringify(T.state()));
T.loadState(round); T.backfill();
check('K it survives a project round trip', T.state().atoms[0].color==='#b71f57', String(T.state().atoms[0].color));
T.clearSel(); T.selectAllActive(); T.startFloat('dup'); T.floTranslate({x:10,y:0}); T.commitFloat();
check('K and a duplicate carries it', T.state().atoms.filter(a=>a.color==='#b71f57').length===2, T.state().atoms.filter(a=>a.color==='#b71f57').length);

console.log('\n--- K  the selection menu offers it');
reset(); ring({x:0,y:0}); T.selectAllActive();
T.showCtx(10,10);
check('K Colour… is in the selection menu', /data-act="color"/.test(document.getElementById('ctxMenu').innerHTML), document.getElementById('ctxMenu').innerHTML.slice(0,120));
T.hideColorPop(); T.selAction('color');
check('K and choosing it opens the panel on the selection', T.cpop()!==null && T.cpop().target.kind==='sel', JSON.stringify(T.cpop()&&T.cpop().target));

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
